backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "blog"
    create: true
    slug: "{{fields.category}}/{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Category", name: "category", widget: "select", options: ["skincare", "haircare"] }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Amazon Link", name: "link", widget: "string" }
